version: "3.7"
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_USER=root
      - POSTGRES_DB=test_db
  application:
    build:
      context: ../hello-world/
      dockerfile: Dockerfile
    depends_on:
      - database