version: "3.7"
services:
 application:
  images: nginx:latest
  ports:
    - "8000:80"
    - "9000:80"
    - target: 80
      published: 8000
      protocol: tcp
      mode: host
    # - "8500-8600:80" Range random port from host machine